### ISSUE TITLE
Error raised

### ISSUE THREAD

**Issue by jihyunlee** [TakahiroMiyaura/HoloOcrSamples#1]
Hi Takahiro-san, 

I am trying to deploy to Hololens and successfully ran but it shows an error as below:

```
Exception thrown: 'System.ArgumentNullException' in System.Linq.dll
ArgumentNullException: Value cannot be null.
Parameter name: source
   at System.Linq.Enumerable.OfType[TResult](IEnumerable source)
   at UWPBridgeService.GetService[T]()
   at CameraScript.Update()
   at CameraScript.$Invoke9Update(Int64 instance, Int64* args)
   at UnityEngine.Internal.$MethodUtility.InvokeMethod(Int64 instance, Int64* args, IntPtr method) 
(Filename: <Unknown> Line: 0)
```

The way I did is.. open the folder in Unity and build.
Then open solution file and deploy to Hololense. [reference](https://developer.microsoft.com/en-us/windows/holographic/exporting_and_building_a_unity_visual_studio_solution#how_to_export_from_unity)
But it seems like the solution doesn't include /UWP/HoloOcrSamples/* files..
so that class OcrService not found, which means never addService called..

I wonder if I miss something to run the project correctly. Please help :)

Arigato,
Jihyun

**Comment by TakahiroMiyaura** [comment]
Hi Jihyun,

As a result of me checking the repository, it seems that I forgot some files must upload. I pushed Missing files to the repository.
Sorry, please obtain the latest version.
The cause of the exception is the UWP application's Capabilities setting.
This UWP application uses a video device, so it is necessary to enable Capabilities ('webcam' and 'microphone') of the UWP application.
I forgot to upload 'Package.appxmanifest', so build application is missing Capabilities , and you couldn't execute 
Because the application did not have enough authority, it failed initialization of 'OcrService'.

Thank you for pointing out.
Thanks to you, I got a hint to revise to more better program.:)

**Comment by sw-ms-krutarthbhatt** [comment]
Hi Takahiro-san,

Added necessary Capability for the UWP application but still I am getting this error 

Exception thrown: 'System.ArgumentNullException' in System.Linq.dll
ArgumentNullException: Value cannot be null.
Parameter name: source
   at System.Linq.Enumerable.OfType[TResult](IEnumerable source)
   at UWPBridgeService.GetService[T]()
   at CameraScript.Update()
   at CameraScript.$Invoke9(Int64 instance, Int64* args)
   at UnityEngine.Internal.$MethodUtility.InvokeMethod(Int64 instance, Int64* args, IntPtr method) 
(Filename: <Unknown> Line: 0)

Can you please help!

Thanks

**Comment by TakahiroMiyaura** [comment]
Hi sw-ms-krutarthbhatt,

Thanks for letting me know.

When you build unity project,you selected "[HoloOcrSamples\UWP](https://github.com/TakahiroMiyaura/HoloOcrSamples/tree/master/UWP/HoloOcrSamples)" folder?
if you selected different folder,please select "[HoloOcrSamples\UWP](https://github.com/TakahiroMiyaura/HoloOcrSamples/tree/master/UWP/HoloOcrSamples)" folder.

This Sample code use "Windows.Media.Ocr.OCREngine",therefore after build with Unity,we must modify a part of UWP source code.
I have putting the source code that has already modified completed in this folder.
  
Please try to build Unity Project in "[HoloOcrSamples\UWP](https://github.com/TakahiroMiyaura/HoloOcrSamples/tree/master/UWP/HoloOcrSamples)" folder.

![image](https://user-images.githubusercontent.com/8484268/44945174-5f8b0b80-ae1e-11e8-942e-90a8e0da4218.png)

Thank you for your patience and cooperation.
Best regards.

**Comment by sw-ms-krutarthbhatt** [comment]
Hi Takahiro-san,

Thanks for the response and directing me...
Build project as per your instructions and when I try to load project to HoloLens I am facing this errors

Error : Cannot resolve Assembly or Windows Metadata file 'UnityEngine.CoreModule.dll'
Error : Type universe cannot resolve assembly: UnityEngine.CoreModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null.

see attached Image

![capture](https://user-images.githubusercontent.com/3853747/45072768-0fe86080-b0fa-11e8-93c8-8abb3a2a676e.PNG)


Thanks.

**Comment by TakahiroMiyaura** [comment]
Hi sw-ms-krutarthbhatt,

Thanks for confirming.

huum...
I have investigating this matter,but I cannot identify the cause yet.
It may take me time to answer that.

If it would be possible,Can you tell me the follow information?:
・OS edition,version(ex:win10 Pro 1803)
・Unity version
・Visual Studio version
・Build Settings on Unity(attached image also will do)

Thanks.

**Comment by sw-ms-krutarthbhatt** [comment]
Miyaura,
Here are the information
- OS edition : Windows 10 Pro 
- version : 1803
- Unity version : Unity 2018.2.4f1
- Visual Studio version : 2017
- Build Settings on Unity : attached image 

![buildsettings](https://user-images.githubusercontent.com/3853747/45278569-59b2bb80-b4eb-11e8-81b0-7c7863fc3603.PNG)

Thanks.

**Comment by TakahiroMiyaura** [comment]
Hi sw-ms-krutarthbhatt,

Thanks for information.

Confirm it,I could understand to issues that you can't build this project.
When I developed this Project at that time, the environment is:

- Windows 10 Pro
- Windows SDK 10.0.14393.0
- Visual Stuido 2015
- Unity 5.5.0

For the reason,you couldn't build it.

So,I added branch '[Unity2017.2.X](https://github.com/TakahiroMiyaura/HoloOcrSamples/tree/Unity2017.2.X)'.
the environments is : 

- Windows 10 Pro
- Windows SDK 10.0.17134.0
- Visual Studio 2017
- Unity 2017.2.1p2 

Please pull again, and checkout '[Unity2017.2.X](https://github.com/TakahiroMiyaura/HoloOcrSamples/tree/Unity2017.2.X)'.

Thanks.
